### PR TITLE
Add KMS v2 support

### PR DESCRIPTION
**Pull request by sethvargo**
This PR builds on top of @sshcherbakov's PR, uses interfaces in a more idiomatic way.

### CODE REVIEW

**Comment by sshcherbakov** [comment]
Thank you very much, Seth, really appreciate this!
Unfortunately, the tests are failing in the `plugin/v2` at the moment.

**Comment by sethvargo** [comment]
@sshcherbakov fixed

**Comment by sshcherbakov** [comment]
Thank you very much, @sethvargo 
Everything's perfect now. I see the ideomatic approach, it is cleaner indeed.
The local build, cloud build and unit tests are working for me now.
I've checked this plugin version in my test cluster and it looks good as well.

@hoskeri this PR also addresses the remaining concurrent access to the shared state in the program. With that do you think we are ready to merge?

**Comment by hoskeri** [comment]
Yup, merged.

**Pull request merged**
